version: '3.7'
services:

  mysql:  
    image: app/mysql:5.7
    container_name: app_mysql
    build:
      context: .
      dockerfile: ${DOCKER_SERVICE}/mysql/v5.7/Dockerfile    
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_SERVICE}/mysql/data:/var/lib/mysql:rw
      - ${DOCKER_SERVICE}/mysql/logs:/var/log/mysql:rw
      - ${DOCKER_SERVICE}/mysql/v5.7/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: Xq54tGxtZt4MJha
    restart: always
    command: "--character-set-server=utf8"
    networks:
      - app

networks:
  app:
    name: app # `docker network ls` 查询 && 根据实际填写