version: '3.7'
services:

  mysql:  
    image: app/mysql:5.7
    container_name: app_mysql
    build:
      context: .
      dockerfile: ./services/mysql/Dockerfile    
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql:rw
      - ./services/mysql/log:/var/log/mysql:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    command: "--character-set-server=utf8"
    networks:
      - app

networks:
  app:
    name: app # `docker network ls` 查询 && 根据实际填写