version: '3.7'
services:
  nginx:
    image: app/nginx:1.15
    container_name: app_nginx
    build:
      context: .
      dockerfile: ${DOCKER_SERVICE}/nginx/${dockerfile}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APP_PATH}:/app:rw
      - ${DOCKER_SERVICE}/nginx/etc/conf.d:/etc/nginx/conf.d
      - ${DOCKER_SERVICE}/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro      
    restart: always
    command: nginx -g 'daemon off;'
    networks:
      - app
    external_links:  # links 为 services name, 官方已废弃 links 参数
      - php:php-fpm         

networks:
  app:
    name: app # `docker network ls` 查询 && 根据实际填写
