version: '3.7'

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true  # 赋予该进程更多的特权
    hostname: vpn
    container_name: app_vpn
    networks:
      - app      

networks:
  app:
    name: vpn # `docker network ls` 查询 && 根据实际填写    
